### PR TITLE
increase powerdns apiKey max lenght

### LINKED ISSUE #575: PowerDNS apiKey length validation is too restrictive
**What happened**:
`Error while waiting for DNSProvider shoot--400232--optest1/powerdns-shoot-dns-service-dns-400232 to become ready: state Error: validation failed for property apiKey (alias for ApiKey): value exceeds maximum length of 128 characters`

https://github.com/gardener/external-dns-management/blob/d5314f4d68a2a6deb29fc3b43bc44906813f6741/pkg/controller/provider/powerdns/factory.go#L40-L41

**What you expected to happen**:
Was there a specific reason to limit the apiKey to just 128 characters?

We use a auth proxy infront of PowerDNS with a JWT Token which is usually longer than 128 characters.
Since this is just a HTTP Header which afaik can go up to 8k bytes maybe a bit larger like a 1000 characters would good.

### PR DESCRIPTION
**Pull request by Lappihuan**
**How to categorize this PR?**
/kind bug

**What this PR does / why we need it**:
Increases the apiKey max length for powerdns

**Which issue(s) this PR fixes**:
Fixes #575

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Increased maximum length of PowerDNS provider `apiKey` to `8192`.
```

### CODE REVIEW

File: pkg/controller/provider/powerdns/factory.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func newAdapter() provider.DNSHandlerAdapter {
 	checks.Add(provider.RequiredProperty("Server", "server").
 		Validators(provider.NoTrailingWhitespaceValidator, provider.PrintableValidator, provider.URLValidator("https", "http"), provider.MaxLengthValidator(256)))
 	checks.Add(provider.RequiredProperty("ApiKey", "apiKey").
-		Validators(provider.NoTrailingWhitespaceValidator, provider.PrintableValidator, provider.MaxLengthValidator(128)).
+		Validators(provider.NoTrailingWhitespaceValidator, provider.PrintableValidator, provider.MaxLengthValidator(8192)).
```
Comment (marc1404) [inline pkg/controller/provider/powerdns/factory.go:41]: nit: Could you add a comment explaining why we're using `8192` as the maximum length?
```suggestion
		Validators(provider.NoTrailingWhitespaceValidator, provider.PrintableValidator, provider.MaxLengthValidator(8192)). // PowerDNS does not impose a maximum length for API keys. Therefore, the typical maximum length of HTTP headers is used.
```

**Review by marc1404 — COMMENTED** [review]
Thanks for directly opening a PR! 🙏

**Review by marc1404 — COMMENTED** [review]
Fantastic, thanks :)

/lgtm
/approve
